/* eslint-disable */
export default async () => {
    const t = {
        ["./enums/UserTypes.enum"]: await import("./enums/UserTypes.enum"),
        ["./schemas/user.schema"]: await import("./schemas/user.schema"),
        ["./users/public-user-properties"]: await import("./users/public-user-properties"),
        ["./schemas/trading-partners.schema"]: await import("./schemas/trading-partners.schema"),
        ["./schemas/inventory.schema"]: await import("./schemas/inventory.schema"),
        ["./inventory/inventory-logs.service"]: await import("./inventory/inventory-logs.service"),
        ["./schemas/inventory-logs.schema"]: await import("./schemas/inventory-logs.schema")
    };
    return { "@nestjs/swagger": { "models": [[import("./auth/dtos/sign-in.dto"), { "SignInDto": { email: { required: true, type: () => String }, password: { required: true, type: () => String } } }], [import("./auth/dtos/sign-up.dto"), { "SignUpDto": { email: { required: true, type: () => String }, name: { required: true, type: () => String, minLength: 2, maxLength: 50 }, password: { required: true, type: () => String, maxLength: 50 }, roles: { required: true, type: () => [String] } } }], [import("./shared/dtos/param.dto"), { "ParamDto": { id: { required: true, type: () => String } } }], [import("./trading-partners/dtos/partner-details.dto"), { "PartnerDetailsDto": { name: { required: true, type: () => String }, email: { required: false, type: () => String }, type: { required: true, enum: t["./enums/UserTypes.enum"].PartnerType }, companyName: { required: false, type: () => String } } }], [import("./inventory/dtos/product.dto"), { "ProductDto": { productName: { required: true, type: () => String }, productDescription: { required: false, type: () => String }, quantity: { required: true, type: () => Number }, currentPricePerUnit: { required: true, type: () => Number, minimum: 0 } }, "UpdateProductDto": {}, "UpdatePriceDto": {} }], [import("./inventory/dtos/update-quantity.dto"), { "UpdateQuantityDto": { quantity: { required: true, type: () => Number }, isSelling: { required: true, type: () => Boolean } } }]], "controllers": [[import("./auth/auth.controller"), { "AuthController": { "signUp": { type: t["./schemas/user.schema"].User }, "signIn": {}, "signOut": { type: Object } } }], [import("./users/user.controller"), { "UserController": { "getAllUser": { type: [t["./schemas/user.schema"].User] }, "getUserInfo": { type: t["./users/public-user-properties"].PublicUserProperties }, "removeUser": {} } }], [import("./trading-partners/trading-partners.controller"), { "TradingPartnersController": { "getAll": { type: [t["./schemas/trading-partners.schema"].TradingPartner] }, "addPartner": { type: Object }, "removePartner": { type: Object } } }], [import("./inventory/inventory.controller"), { "InventoryController": { "addNewProduct": { type: t["./schemas/inventory.schema"].Inventory }, "getAllProducts": { type: [t["./schemas/inventory.schema"].Inventory] }, "updateProduct": { type: t["./schemas/inventory.schema"].Inventory }, "updateQuantity": { type: t["./schemas/inventory.schema"].Inventory }, "updatePrice": { type: t["./schemas/inventory.schema"].Inventory }, "getProductHistory": { type: [t["./schemas/inventory-logs.schema"].InventoryLogs] }, "getAllProductHistory": { type: [t["./schemas/inventory-logs.schema"].InventoryLogs] } } }]] } };
};